#!/usr/bin/env node

var parseArgs = require('minimist');
var path = require('path');
var fs = require('fs');
var webppl = require('webppl')
var webppl_main = require('../node_modules/webppl/src/main');
var util = require('../node_modules/webppl/src/util');
var pkg = require('../node_modules/webppl/src/pkg');

function printWebPPLValue(x) {
  // if (isErp(x)) {
  //   x.print();
  // } else {
    // console.log(x)
    console.log(util.serialize(x));
  // }
};

function main() {

	   var argv = parseArgs(process.argv.slice(2));
     var programFile = argv._[0];

    var code = fs.readFileSync(programFile, 'utf8');

    var packagePaths = [
      path.join(path.dirname(programFile), 'node_modules'),
      pkg.globalPkgDir()
    ];

  var packages = util.asArray(argv.require).map(function(name_or_path) {
    return pkg.load(pkg.read(name_or_path, packagePaths, argv.verbose));
  });

  packages.forEach(function(pkg) {
    if (pkg.js) { global[pkg.js.identifier] = require(pkg.js.path); }
    pkg.headers.forEach(webppl.requireHeader);
  });

	webppl.run(code, function(s,x) {
	  printWebPPLValue(x);
	}, {
    extra: webppl_main.parsePackageCode(packages, false)
  })
}

main();