#!/usr/bin/env node

var webppl = require('./webppl')
var webppl_main = require('./webppl/src/main');
var util = require('./webppl/src/util');
var pkg = require('./webppl/src/pkg');
var argv = require('./webppl/node_modules/minimist')(process.argv.slice(2));
var path = require('path');
var fs = require('fs');


function writeWebPPLValue(x, file) {
  if (dists.isDist(x) && x.isContinuous) {
    var serialized_x = util.serialize(x.toString());
  } else if (dists.isDist(x) && x.samples) {
    var serialized_x = util.serialize(x.samples);
  } else {
    var serialized_x = util.serialize(x);
  }
  // write to a temporary file and then rename it to output file name, so that
  // creating the output file is atomic
  fs.writeFileSync(file + "_tmp", serialized_x + "\n");
  fs.renameSync(file + "_tmp", file);
};


function main() {
  var code = fs.readFileSync(argv.programFile, 'utf8');

  var packagePaths = [
    path.join(path.dirname(argv.programFile), 'node_modules'),
    pkg.globalPkgDir()
  ];

  var packages = util.asArray(argv.require).map(function(name_or_path) {
    return pkg.load(pkg.read(name_or_path, packagePaths, argv.verbose));
  });

  packages.forEach(function(pkg) {
    if (pkg.js) { global[pkg.js.identifier] = require(pkg.js.path); }
    pkg.headers.forEach(webppl.requireHeader);
  });

  webppl.run(code, function(s,x) {
    writeWebPPLValue(x, argv.outputFile);
  }, {
    bundles: webppl_main.parsePackageCode(packages, false)
  });

}

try {
  main();
} finally {
  fs.writeFileSync(argv.finishFile,  "");
}
